version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: ["bun", "run", "start:backend"]

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/usr/src/app
    command: ["bun", "run", "start:web"]

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
    command: ["bun", "run", "start:websocket"]
